/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as HeroesRouteImport } from './routes/heroes'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoadoutsRouteImport } from './routes/loadouts'
import { Route as MissionsGuideRouteImport } from './routes/missions-guide'
import { Route as SchematicsRouteImport } from './routes/schematics'
import { Route as VbucksMissionsRouteImport } from './routes/vbucks-missions'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleArticlesRouteImport } from './routes/$locale.articles'
import { Route as LocaleGuidesRouteImport } from './routes/$locale.guides'
import { Route as LocaleHeroesRouteImport } from './routes/$locale.heroes'
import { Route as LocaleInventoryRouteImport } from './routes/$locale.inventory'
import { Route as LocaleLoadoutsRouteImport } from './routes/$locale.loadouts'
import { Route as LocaleMissionsGuideRouteImport } from './routes/$locale/missions-guide'
import { Route as LocaleSchematicsRouteImport } from './routes/$locale.schematics'
import { Route as LocaleVbucksMissionsRouteImport } from './routes/$locale/vbucks-missions'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminArticlesRouteImport } from './routes/admin/articles'
import { Route as AdminHeroesRouteImport } from './routes/admin/heroes'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminLoadoutsRouteImport } from './routes/admin/loadouts'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminPublishingRouteImport } from './routes/admin/publishing'
import { Route as AdminSeoRouteImport } from './routes/admin/seo'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ArticlesPreviewRouteImport } from './routes/articles.preview'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as GuidesPreviewRouteImport } from './routes/guides.preview'
import { Route as HeroesSlugRouteImport } from './routes/heroes.$slug'
import { Route as InventorySlugRouteImport } from './routes/inventory.$slug'
import { Route as LoadoutsSlugRouteImport } from './routes/loadouts.$slug'
import { Route as SchematicsSlugRouteImport } from './routes/schematics.$slug'
import { Route as LocaleArticlesSlugRouteImport } from './routes/$locale.articles.$slug'
import { Route as LocaleGuidesSlugRouteImport } from './routes/$locale.guides.$slug'
import { Route as LocaleHeroesSlugRouteImport } from './routes/$locale.heroes.$slug'
import { Route as LocaleInventorySlugRouteImport } from './routes/$locale.inventory.$slug'
import { Route as LocaleLoadoutsSlugRouteImport } from './routes/$locale.loadouts.$slug'
import { Route as LocaleSchematicsSlugRouteImport } from './routes/$locale.schematics.$slug'
import { Route as AdminArticlesContentIdRouteImport } from './routes/admin/articles.$contentId'
import { Route as AdminHeroesContentIdRouteImport } from './routes/admin/heroes.$contentId'
import { Route as AdminInventoryContentIdRouteImport } from './routes/admin/inventory.$contentId'
import { Route as AdminLoadoutsContentIdRouteImport } from './routes/admin/loadouts.$contentId'
import { Route as GuidesTopicsTopicRouteImport } from './routes/guides.topics.$topic'
import { Route as LocaleGuidesTopicsTopicRouteImport } from './routes/$locale.guides.topics.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesRoute = HeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadoutsRoute = LoadoutsRouteImport.update({
  id: '/loadouts',
  path: '/loadouts',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsGuideRoute = MissionsGuideRouteImport.update({
  id: '/missions-guide',
  path: '/missions-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SchematicsRoute = SchematicsRouteImport.update({
  id: '/schematics',
  path: '/schematics',
  getParentRoute: () => rootRouteImport,
} as any)
const VbucksMissionsRoute = VbucksMissionsRouteImport.update({
  id: '/vbucks-missions',
  path: '/vbucks-missions',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/$locale/about',
  path: '/$locale/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleArticlesRoute = LocaleArticlesRouteImport.update({
  id: '/$locale/articles',
  path: '/$locale/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleGuidesRoute = LocaleGuidesRouteImport.update({
  id: '/$locale/guides',
  path: '/$locale/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleHeroesRoute = LocaleHeroesRouteImport.update({
  id: '/$locale/heroes',
  path: '/$locale/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleInventoryRoute = LocaleInventoryRouteImport.update({
  id: '/$locale/inventory',
  path: '/$locale/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleLoadoutsRoute = LocaleLoadoutsRouteImport.update({
  id: '/$locale/loadouts',
  path: '/$locale/loadouts',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleMissionsGuideRoute = LocaleMissionsGuideRouteImport.update({
  id: '/$locale/missions-guide',
  path: '/$locale/missions-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSchematicsRoute = LocaleSchematicsRouteImport.update({
  id: '/$locale/schematics',
  path: '/$locale/schematics',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleVbucksMissionsRoute = LocaleVbucksMissionsRouteImport.update({
  id: '/$locale/vbucks-missions',
  path: '/$locale/vbucks-missions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/admin/articles',
  path: '/admin/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHeroesRoute = AdminHeroesRouteImport.update({
  id: '/admin/heroes',
  path: '/admin/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoadoutsRoute = AdminLoadoutsRouteImport.update({
  id: '/admin/loadouts',
  path: '/admin/loadouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPublishingRoute = AdminPublishingRouteImport.update({
  id: '/admin/publishing',
  path: '/admin/publishing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesPreviewRoute = ArticlesPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ArticlesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesPreviewRoute = GuidesPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => GuidesRoute,
} as any)
const HeroesSlugRoute = HeroesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HeroesRoute,
} as any)
const InventorySlugRoute = InventorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InventoryRoute,
} as any)
const LoadoutsSlugRoute = LoadoutsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LoadoutsRoute,
} as any)
const SchematicsSlugRoute = SchematicsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SchematicsRoute,
} as any)
const LocaleArticlesSlugRoute = LocaleArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleArticlesRoute,
} as any)
const LocaleGuidesSlugRoute = LocaleGuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleGuidesRoute,
} as any)
const LocaleHeroesSlugRoute = LocaleHeroesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleHeroesRoute,
} as any)
const LocaleInventorySlugRoute = LocaleInventorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleInventoryRoute,
} as any)
const LocaleLoadoutsSlugRoute = LocaleLoadoutsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleLoadoutsRoute,
} as any)
const LocaleSchematicsSlugRoute = LocaleSchematicsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleSchematicsRoute,
} as any)
const AdminArticlesContentIdRoute = AdminArticlesContentIdRouteImport.update({
  id: '/$contentId',
  path: '/$contentId',
  getParentRoute: () => AdminArticlesRoute,
} as any)
const AdminHeroesContentIdRoute = AdminHeroesContentIdRouteImport.update({
  id: '/$contentId',
  path: '/$contentId',
  getParentRoute: () => AdminHeroesRoute,
} as any)
const AdminInventoryContentIdRoute = AdminInventoryContentIdRouteImport.update({
  id: '/$contentId',
  path: '/$contentId',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const AdminLoadoutsContentIdRoute = AdminLoadoutsContentIdRouteImport.update({
  id: '/$contentId',
  path: '/$contentId',
  getParentRoute: () => AdminLoadoutsRoute,
} as any)
const GuidesTopicsTopicRoute = GuidesTopicsTopicRouteImport.update({
  id: '/topics/$topic',
  path: '/topics/$topic',
  getParentRoute: () => GuidesRoute,
} as any)
const LocaleGuidesTopicsTopicRoute = LocaleGuidesTopicsTopicRouteImport.update({
  id: '/topics/$topic',
  path: '/topics/$topic',
  getParentRoute: () => LocaleGuidesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/guides': typeof GuidesRouteWithChildren
  '/heroes': typeof HeroesRouteWithChildren
  '/inventory': typeof InventoryRouteWithChildren
  '/loadouts': typeof LoadoutsRouteWithChildren
  '/missions-guide': typeof MissionsGuideRoute
  '/schematics': typeof SchematicsRouteWithChildren
  '/vbucks-missions': typeof VbucksMissionsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/articles': typeof LocaleArticlesRouteWithChildren
  '/$locale/guides': typeof LocaleGuidesRouteWithChildren
  '/$locale/heroes': typeof LocaleHeroesRouteWithChildren
  '/$locale/inventory': typeof LocaleInventoryRouteWithChildren
  '/$locale/loadouts': typeof LocaleLoadoutsRouteWithChildren
  '/$locale/missions-guide': typeof LocaleMissionsGuideRoute
  '/$locale/schematics': typeof LocaleSchematicsRouteWithChildren
  '/$locale/vbucks-missions': typeof LocaleVbucksMissionsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/heroes': typeof AdminHeroesRouteWithChildren
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/loadouts': typeof AdminLoadoutsRouteWithChildren
  '/admin/media': typeof AdminMediaRoute
  '/admin/publishing': typeof AdminPublishingRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/preview': typeof ArticlesPreviewRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/preview': typeof GuidesPreviewRoute
  '/heroes/$slug': typeof HeroesSlugRoute
  '/inventory/$slug': typeof InventorySlugRoute
  '/loadouts/$slug': typeof LoadoutsSlugRoute
  '/schematics/$slug': typeof SchematicsSlugRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$locale/articles/$slug': typeof LocaleArticlesSlugRoute
  '/$locale/guides/$slug': typeof LocaleGuidesSlugRoute
  '/$locale/heroes/$slug': typeof LocaleHeroesSlugRoute
  '/$locale/inventory/$slug': typeof LocaleInventorySlugRoute
  '/$locale/loadouts/$slug': typeof LocaleLoadoutsSlugRoute
  '/$locale/schematics/$slug': typeof LocaleSchematicsSlugRoute
  '/admin/articles/$contentId': typeof AdminArticlesContentIdRoute
  '/admin/heroes/$contentId': typeof AdminHeroesContentIdRoute
  '/admin/inventory/$contentId': typeof AdminInventoryContentIdRoute
  '/admin/loadouts/$contentId': typeof AdminLoadoutsContentIdRoute
  '/guides/topics/$topic': typeof GuidesTopicsTopicRoute
  '/$locale/guides/topics/$topic': typeof LocaleGuidesTopicsTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/guides': typeof GuidesRouteWithChildren
  '/heroes': typeof HeroesRouteWithChildren
  '/inventory': typeof InventoryRouteWithChildren
  '/loadouts': typeof LoadoutsRouteWithChildren
  '/missions-guide': typeof MissionsGuideRoute
  '/schematics': typeof SchematicsRouteWithChildren
  '/vbucks-missions': typeof VbucksMissionsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/articles': typeof LocaleArticlesRouteWithChildren
  '/$locale/guides': typeof LocaleGuidesRouteWithChildren
  '/$locale/heroes': typeof LocaleHeroesRouteWithChildren
  '/$locale/inventory': typeof LocaleInventoryRouteWithChildren
  '/$locale/loadouts': typeof LocaleLoadoutsRouteWithChildren
  '/$locale/missions-guide': typeof LocaleMissionsGuideRoute
  '/$locale/schematics': typeof LocaleSchematicsRouteWithChildren
  '/$locale/vbucks-missions': typeof LocaleVbucksMissionsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/heroes': typeof AdminHeroesRouteWithChildren
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/loadouts': typeof AdminLoadoutsRouteWithChildren
  '/admin/media': typeof AdminMediaRoute
  '/admin/publishing': typeof AdminPublishingRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/preview': typeof ArticlesPreviewRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/preview': typeof GuidesPreviewRoute
  '/heroes/$slug': typeof HeroesSlugRoute
  '/inventory/$slug': typeof InventorySlugRoute
  '/loadouts/$slug': typeof LoadoutsSlugRoute
  '/schematics/$slug': typeof SchematicsSlugRoute
  '/$locale': typeof LocaleIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$locale/articles/$slug': typeof LocaleArticlesSlugRoute
  '/$locale/guides/$slug': typeof LocaleGuidesSlugRoute
  '/$locale/heroes/$slug': typeof LocaleHeroesSlugRoute
  '/$locale/inventory/$slug': typeof LocaleInventorySlugRoute
  '/$locale/loadouts/$slug': typeof LocaleLoadoutsSlugRoute
  '/$locale/schematics/$slug': typeof LocaleSchematicsSlugRoute
  '/admin/articles/$contentId': typeof AdminArticlesContentIdRoute
  '/admin/heroes/$contentId': typeof AdminHeroesContentIdRoute
  '/admin/inventory/$contentId': typeof AdminInventoryContentIdRoute
  '/admin/loadouts/$contentId': typeof AdminLoadoutsContentIdRoute
  '/guides/topics/$topic': typeof GuidesTopicsTopicRoute
  '/$locale/guides/topics/$topic': typeof LocaleGuidesTopicsTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/guides': typeof GuidesRouteWithChildren
  '/heroes': typeof HeroesRouteWithChildren
  '/inventory': typeof InventoryRouteWithChildren
  '/loadouts': typeof LoadoutsRouteWithChildren
  '/missions-guide': typeof MissionsGuideRoute
  '/schematics': typeof SchematicsRouteWithChildren
  '/vbucks-missions': typeof VbucksMissionsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/articles': typeof LocaleArticlesRouteWithChildren
  '/$locale/guides': typeof LocaleGuidesRouteWithChildren
  '/$locale/heroes': typeof LocaleHeroesRouteWithChildren
  '/$locale/inventory': typeof LocaleInventoryRouteWithChildren
  '/$locale/loadouts': typeof LocaleLoadoutsRouteWithChildren
  '/$locale/missions-guide': typeof LocaleMissionsGuideRoute
  '/$locale/schematics': typeof LocaleSchematicsRouteWithChildren
  '/$locale/vbucks-missions': typeof LocaleVbucksMissionsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/heroes': typeof AdminHeroesRouteWithChildren
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/loadouts': typeof AdminLoadoutsRouteWithChildren
  '/admin/media': typeof AdminMediaRoute
  '/admin/publishing': typeof AdminPublishingRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/preview': typeof ArticlesPreviewRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/preview': typeof GuidesPreviewRoute
  '/heroes/$slug': typeof HeroesSlugRoute
  '/inventory/$slug': typeof InventorySlugRoute
  '/loadouts/$slug': typeof LoadoutsSlugRoute
  '/schematics/$slug': typeof SchematicsSlugRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$locale/articles/$slug': typeof LocaleArticlesSlugRoute
  '/$locale/guides/$slug': typeof LocaleGuidesSlugRoute
  '/$locale/heroes/$slug': typeof LocaleHeroesSlugRoute
  '/$locale/inventory/$slug': typeof LocaleInventorySlugRoute
  '/$locale/loadouts/$slug': typeof LocaleLoadoutsSlugRoute
  '/$locale/schematics/$slug': typeof LocaleSchematicsSlugRoute
  '/admin/articles/$contentId': typeof AdminArticlesContentIdRoute
  '/admin/heroes/$contentId': typeof AdminHeroesContentIdRoute
  '/admin/inventory/$contentId': typeof AdminInventoryContentIdRoute
  '/admin/loadouts/$contentId': typeof AdminLoadoutsContentIdRoute
  '/guides/topics/$topic': typeof GuidesTopicsTopicRoute
  '/$locale/guides/topics/$topic': typeof LocaleGuidesTopicsTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/articles'
    | '/guides'
    | '/heroes'
    | '/inventory'
    | '/loadouts'
    | '/missions-guide'
    | '/schematics'
    | '/vbucks-missions'
    | '/$locale/about'
    | '/$locale/articles'
    | '/$locale/guides'
    | '/$locale/heroes'
    | '/$locale/inventory'
    | '/$locale/loadouts'
    | '/$locale/missions-guide'
    | '/$locale/schematics'
    | '/$locale/vbucks-missions'
    | '/admin/activity'
    | '/admin/articles'
    | '/admin/heroes'
    | '/admin/inventory'
    | '/admin/loadouts'
    | '/admin/media'
    | '/admin/publishing'
    | '/admin/seo'
    | '/admin/settings'
    | '/articles/$slug'
    | '/articles/preview'
    | '/guides/$slug'
    | '/guides/preview'
    | '/heroes/$slug'
    | '/inventory/$slug'
    | '/loadouts/$slug'
    | '/schematics/$slug'
    | '/$locale/'
    | '/admin/'
    | '/$locale/articles/$slug'
    | '/$locale/guides/$slug'
    | '/$locale/heroes/$slug'
    | '/$locale/inventory/$slug'
    | '/$locale/loadouts/$slug'
    | '/$locale/schematics/$slug'
    | '/admin/articles/$contentId'
    | '/admin/heroes/$contentId'
    | '/admin/inventory/$contentId'
    | '/admin/loadouts/$contentId'
    | '/guides/topics/$topic'
    | '/$locale/guides/topics/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/articles'
    | '/guides'
    | '/heroes'
    | '/inventory'
    | '/loadouts'
    | '/missions-guide'
    | '/schematics'
    | '/vbucks-missions'
    | '/$locale/about'
    | '/$locale/articles'
    | '/$locale/guides'
    | '/$locale/heroes'
    | '/$locale/inventory'
    | '/$locale/loadouts'
    | '/$locale/missions-guide'
    | '/$locale/schematics'
    | '/$locale/vbucks-missions'
    | '/admin/activity'
    | '/admin/articles'
    | '/admin/heroes'
    | '/admin/inventory'
    | '/admin/loadouts'
    | '/admin/media'
    | '/admin/publishing'
    | '/admin/seo'
    | '/admin/settings'
    | '/articles/$slug'
    | '/articles/preview'
    | '/guides/$slug'
    | '/guides/preview'
    | '/heroes/$slug'
    | '/inventory/$slug'
    | '/loadouts/$slug'
    | '/schematics/$slug'
    | '/$locale'
    | '/admin'
    | '/$locale/articles/$slug'
    | '/$locale/guides/$slug'
    | '/$locale/heroes/$slug'
    | '/$locale/inventory/$slug'
    | '/$locale/loadouts/$slug'
    | '/$locale/schematics/$slug'
    | '/admin/articles/$contentId'
    | '/admin/heroes/$contentId'
    | '/admin/inventory/$contentId'
    | '/admin/loadouts/$contentId'
    | '/guides/topics/$topic'
    | '/$locale/guides/topics/$topic'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/articles'
    | '/guides'
    | '/heroes'
    | '/inventory'
    | '/loadouts'
    | '/missions-guide'
    | '/schematics'
    | '/vbucks-missions'
    | '/$locale/about'
    | '/$locale/articles'
    | '/$locale/guides'
    | '/$locale/heroes'
    | '/$locale/inventory'
    | '/$locale/loadouts'
    | '/$locale/missions-guide'
    | '/$locale/schematics'
    | '/$locale/vbucks-missions'
    | '/admin/activity'
    | '/admin/articles'
    | '/admin/heroes'
    | '/admin/inventory'
    | '/admin/loadouts'
    | '/admin/media'
    | '/admin/publishing'
    | '/admin/seo'
    | '/admin/settings'
    | '/articles/$slug'
    | '/articles/preview'
    | '/guides/$slug'
    | '/guides/preview'
    | '/heroes/$slug'
    | '/inventory/$slug'
    | '/loadouts/$slug'
    | '/schematics/$slug'
    | '/$locale/'
    | '/admin/'
    | '/$locale/articles/$slug'
    | '/$locale/guides/$slug'
    | '/$locale/heroes/$slug'
    | '/$locale/inventory/$slug'
    | '/$locale/loadouts/$slug'
    | '/$locale/schematics/$slug'
    | '/admin/articles/$contentId'
    | '/admin/heroes/$contentId'
    | '/admin/inventory/$contentId'
    | '/admin/loadouts/$contentId'
    | '/guides/topics/$topic'
    | '/$locale/guides/topics/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  GuidesRoute: typeof GuidesRouteWithChildren
  HeroesRoute: typeof HeroesRouteWithChildren
  InventoryRoute: typeof InventoryRouteWithChildren
  LoadoutsRoute: typeof LoadoutsRouteWithChildren
  MissionsGuideRoute: typeof MissionsGuideRoute
  SchematicsRoute: typeof SchematicsRouteWithChildren
  VbucksMissionsRoute: typeof VbucksMissionsRoute
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleArticlesRoute: typeof LocaleArticlesRouteWithChildren
  LocaleGuidesRoute: typeof LocaleGuidesRouteWithChildren
  LocaleHeroesRoute: typeof LocaleHeroesRouteWithChildren
  LocaleInventoryRoute: typeof LocaleInventoryRouteWithChildren
  LocaleLoadoutsRoute: typeof LocaleLoadoutsRouteWithChildren
  LocaleMissionsGuideRoute: typeof LocaleMissionsGuideRoute
  LocaleSchematicsRoute: typeof LocaleSchematicsRouteWithChildren
  LocaleVbucksMissionsRoute: typeof LocaleVbucksMissionsRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminArticlesRoute: typeof AdminArticlesRouteWithChildren
  AdminHeroesRoute: typeof AdminHeroesRouteWithChildren
  AdminInventoryRoute: typeof AdminInventoryRouteWithChildren
  AdminLoadoutsRoute: typeof AdminLoadoutsRouteWithChildren
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPublishingRoute: typeof AdminPublishingRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes': {
      id: '/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof HeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loadouts': {
      id: '/loadouts'
      path: '/loadouts'
      fullPath: '/loadouts'
      preLoaderRoute: typeof LoadoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions-guide': {
      id: '/missions-guide'
      path: '/missions-guide'
      fullPath: '/missions-guide'
      preLoaderRoute: typeof MissionsGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schematics': {
      id: '/schematics'
      path: '/schematics'
      fullPath: '/schematics'
      preLoaderRoute: typeof SchematicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vbucks-missions': {
      id: '/vbucks-missions'
      path: '/vbucks-missions'
      fullPath: '/vbucks-missions'
      preLoaderRoute: typeof VbucksMissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/$locale/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/articles': {
      id: '/$locale/articles'
      path: '/$locale/articles'
      fullPath: '/$locale/articles'
      preLoaderRoute: typeof LocaleArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/guides': {
      id: '/$locale/guides'
      path: '/$locale/guides'
      fullPath: '/$locale/guides'
      preLoaderRoute: typeof LocaleGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/heroes': {
      id: '/$locale/heroes'
      path: '/$locale/heroes'
      fullPath: '/$locale/heroes'
      preLoaderRoute: typeof LocaleHeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/inventory': {
      id: '/$locale/inventory'
      path: '/$locale/inventory'
      fullPath: '/$locale/inventory'
      preLoaderRoute: typeof LocaleInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/loadouts': {
      id: '/$locale/loadouts'
      path: '/$locale/loadouts'
      fullPath: '/$locale/loadouts'
      preLoaderRoute: typeof LocaleLoadoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/missions-guide': {
      id: '/$locale/missions-guide'
      path: '/$locale/missions-guide'
      fullPath: '/$locale/missions-guide'
      preLoaderRoute: typeof LocaleMissionsGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/schematics': {
      id: '/$locale/schematics'
      path: '/$locale/schematics'
      fullPath: '/$locale/schematics'
      preLoaderRoute: typeof LocaleSchematicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/vbucks-missions': {
      id: '/$locale/vbucks-missions'
      path: '/$locale/vbucks-missions'
      fullPath: '/$locale/vbucks-missions'
      preLoaderRoute: typeof LocaleVbucksMissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/admin/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/heroes': {
      id: '/admin/heroes'
      path: '/admin/heroes'
      fullPath: '/admin/heroes'
      preLoaderRoute: typeof AdminHeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/loadouts': {
      id: '/admin/loadouts'
      path: '/admin/loadouts'
      fullPath: '/admin/loadouts'
      preLoaderRoute: typeof AdminLoadoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/publishing': {
      id: '/admin/publishing'
      path: '/admin/publishing'
      fullPath: '/admin/publishing'
      preLoaderRoute: typeof AdminPublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/preview': {
      id: '/articles/preview'
      path: '/preview'
      fullPath: '/articles/preview'
      preLoaderRoute: typeof ArticlesPreviewRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/preview': {
      id: '/guides/preview'
      path: '/preview'
      fullPath: '/guides/preview'
      preLoaderRoute: typeof GuidesPreviewRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/heroes/$slug': {
      id: '/heroes/$slug'
      path: '/$slug'
      fullPath: '/heroes/$slug'
      preLoaderRoute: typeof HeroesSlugRouteImport
      parentRoute: typeof HeroesRoute
    }
    '/inventory/$slug': {
      id: '/inventory/$slug'
      path: '/$slug'
      fullPath: '/inventory/$slug'
      preLoaderRoute: typeof InventorySlugRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/loadouts/$slug': {
      id: '/loadouts/$slug'
      path: '/$slug'
      fullPath: '/loadouts/$slug'
      preLoaderRoute: typeof LoadoutsSlugRouteImport
      parentRoute: typeof LoadoutsRoute
    }
    '/schematics/$slug': {
      id: '/schematics/$slug'
      path: '/$slug'
      fullPath: '/schematics/$slug'
      preLoaderRoute: typeof SchematicsSlugRouteImport
      parentRoute: typeof SchematicsRoute
    }
    '/$locale/articles/$slug': {
      id: '/$locale/articles/$slug'
      path: '/$slug'
      fullPath: '/$locale/articles/$slug'
      preLoaderRoute: typeof LocaleArticlesSlugRouteImport
      parentRoute: typeof LocaleArticlesRoute
    }
    '/$locale/guides/$slug': {
      id: '/$locale/guides/$slug'
      path: '/$slug'
      fullPath: '/$locale/guides/$slug'
      preLoaderRoute: typeof LocaleGuidesSlugRouteImport
      parentRoute: typeof LocaleGuidesRoute
    }
    '/$locale/heroes/$slug': {
      id: '/$locale/heroes/$slug'
      path: '/$slug'
      fullPath: '/$locale/heroes/$slug'
      preLoaderRoute: typeof LocaleHeroesSlugRouteImport
      parentRoute: typeof LocaleHeroesRoute
    }
    '/$locale/inventory/$slug': {
      id: '/$locale/inventory/$slug'
      path: '/$slug'
      fullPath: '/$locale/inventory/$slug'
      preLoaderRoute: typeof LocaleInventorySlugRouteImport
      parentRoute: typeof LocaleInventoryRoute
    }
    '/$locale/loadouts/$slug': {
      id: '/$locale/loadouts/$slug'
      path: '/$slug'
      fullPath: '/$locale/loadouts/$slug'
      preLoaderRoute: typeof LocaleLoadoutsSlugRouteImport
      parentRoute: typeof LocaleLoadoutsRoute
    }
    '/$locale/schematics/$slug': {
      id: '/$locale/schematics/$slug'
      path: '/$slug'
      fullPath: '/$locale/schematics/$slug'
      preLoaderRoute: typeof LocaleSchematicsSlugRouteImport
      parentRoute: typeof LocaleSchematicsRoute
    }
    '/admin/articles/$contentId': {
      id: '/admin/articles/$contentId'
      path: '/$contentId'
      fullPath: '/admin/articles/$contentId'
      preLoaderRoute: typeof AdminArticlesContentIdRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
    '/admin/heroes/$contentId': {
      id: '/admin/heroes/$contentId'
      path: '/$contentId'
      fullPath: '/admin/heroes/$contentId'
      preLoaderRoute: typeof AdminHeroesContentIdRouteImport
      parentRoute: typeof AdminHeroesRoute
    }
    '/admin/inventory/$contentId': {
      id: '/admin/inventory/$contentId'
      path: '/$contentId'
      fullPath: '/admin/inventory/$contentId'
      preLoaderRoute: typeof AdminInventoryContentIdRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/loadouts/$contentId': {
      id: '/admin/loadouts/$contentId'
      path: '/$contentId'
      fullPath: '/admin/loadouts/$contentId'
      preLoaderRoute: typeof AdminLoadoutsContentIdRouteImport
      parentRoute: typeof AdminLoadoutsRoute
    }
    '/guides/topics/$topic': {
      id: '/guides/topics/$topic'
      path: '/topics/$topic'
      fullPath: '/guides/topics/$topic'
      preLoaderRoute: typeof GuidesTopicsTopicRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/$locale/guides/topics/$topic': {
      id: '/$locale/guides/topics/$topic'
      path: '/topics/$topic'
      fullPath: '/$locale/guides/topics/$topic'
      preLoaderRoute: typeof LocaleGuidesTopicsTopicRouteImport
      parentRoute: typeof LocaleGuidesRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesPreviewRoute: typeof ArticlesPreviewRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesPreviewRoute: ArticlesPreviewRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesPreviewRoute: typeof GuidesPreviewRoute
  GuidesTopicsTopicRoute: typeof GuidesTopicsTopicRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesPreviewRoute: GuidesPreviewRoute,
  GuidesTopicsTopicRoute: GuidesTopicsTopicRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface HeroesRouteChildren {
  HeroesSlugRoute: typeof HeroesSlugRoute
}

const HeroesRouteChildren: HeroesRouteChildren = {
  HeroesSlugRoute: HeroesSlugRoute,
}

const HeroesRouteWithChildren =
  HeroesRoute._addFileChildren(HeroesRouteChildren)

interface InventoryRouteChildren {
  InventorySlugRoute: typeof InventorySlugRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventorySlugRoute: InventorySlugRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface LoadoutsRouteChildren {
  LoadoutsSlugRoute: typeof LoadoutsSlugRoute
}

const LoadoutsRouteChildren: LoadoutsRouteChildren = {
  LoadoutsSlugRoute: LoadoutsSlugRoute,
}

const LoadoutsRouteWithChildren = LoadoutsRoute._addFileChildren(
  LoadoutsRouteChildren,
)

interface SchematicsRouteChildren {
  SchematicsSlugRoute: typeof SchematicsSlugRoute
}

const SchematicsRouteChildren: SchematicsRouteChildren = {
  SchematicsSlugRoute: SchematicsSlugRoute,
}

const SchematicsRouteWithChildren = SchematicsRoute._addFileChildren(
  SchematicsRouteChildren,
)

interface LocaleArticlesRouteChildren {
  LocaleArticlesSlugRoute: typeof LocaleArticlesSlugRoute
}

const LocaleArticlesRouteChildren: LocaleArticlesRouteChildren = {
  LocaleArticlesSlugRoute: LocaleArticlesSlugRoute,
}

const LocaleArticlesRouteWithChildren = LocaleArticlesRoute._addFileChildren(
  LocaleArticlesRouteChildren,
)

interface LocaleGuidesRouteChildren {
  LocaleGuidesSlugRoute: typeof LocaleGuidesSlugRoute
  LocaleGuidesTopicsTopicRoute: typeof LocaleGuidesTopicsTopicRoute
}

const LocaleGuidesRouteChildren: LocaleGuidesRouteChildren = {
  LocaleGuidesSlugRoute: LocaleGuidesSlugRoute,
  LocaleGuidesTopicsTopicRoute: LocaleGuidesTopicsTopicRoute,
}

const LocaleGuidesRouteWithChildren = LocaleGuidesRoute._addFileChildren(
  LocaleGuidesRouteChildren,
)

interface LocaleHeroesRouteChildren {
  LocaleHeroesSlugRoute: typeof LocaleHeroesSlugRoute
}

const LocaleHeroesRouteChildren: LocaleHeroesRouteChildren = {
  LocaleHeroesSlugRoute: LocaleHeroesSlugRoute,
}

const LocaleHeroesRouteWithChildren = LocaleHeroesRoute._addFileChildren(
  LocaleHeroesRouteChildren,
)

interface LocaleInventoryRouteChildren {
  LocaleInventorySlugRoute: typeof LocaleInventorySlugRoute
}

const LocaleInventoryRouteChildren: LocaleInventoryRouteChildren = {
  LocaleInventorySlugRoute: LocaleInventorySlugRoute,
}

const LocaleInventoryRouteWithChildren = LocaleInventoryRoute._addFileChildren(
  LocaleInventoryRouteChildren,
)

interface LocaleLoadoutsRouteChildren {
  LocaleLoadoutsSlugRoute: typeof LocaleLoadoutsSlugRoute
}

const LocaleLoadoutsRouteChildren: LocaleLoadoutsRouteChildren = {
  LocaleLoadoutsSlugRoute: LocaleLoadoutsSlugRoute,
}

const LocaleLoadoutsRouteWithChildren = LocaleLoadoutsRoute._addFileChildren(
  LocaleLoadoutsRouteChildren,
)

interface LocaleSchematicsRouteChildren {
  LocaleSchematicsSlugRoute: typeof LocaleSchematicsSlugRoute
}

const LocaleSchematicsRouteChildren: LocaleSchematicsRouteChildren = {
  LocaleSchematicsSlugRoute: LocaleSchematicsSlugRoute,
}

const LocaleSchematicsRouteWithChildren =
  LocaleSchematicsRoute._addFileChildren(LocaleSchematicsRouteChildren)

interface AdminArticlesRouteChildren {
  AdminArticlesContentIdRoute: typeof AdminArticlesContentIdRoute
}

const AdminArticlesRouteChildren: AdminArticlesRouteChildren = {
  AdminArticlesContentIdRoute: AdminArticlesContentIdRoute,
}

const AdminArticlesRouteWithChildren = AdminArticlesRoute._addFileChildren(
  AdminArticlesRouteChildren,
)

interface AdminHeroesRouteChildren {
  AdminHeroesContentIdRoute: typeof AdminHeroesContentIdRoute
}

const AdminHeroesRouteChildren: AdminHeroesRouteChildren = {
  AdminHeroesContentIdRoute: AdminHeroesContentIdRoute,
}

const AdminHeroesRouteWithChildren = AdminHeroesRoute._addFileChildren(
  AdminHeroesRouteChildren,
)

interface AdminInventoryRouteChildren {
  AdminInventoryContentIdRoute: typeof AdminInventoryContentIdRoute
}

const AdminInventoryRouteChildren: AdminInventoryRouteChildren = {
  AdminInventoryContentIdRoute: AdminInventoryContentIdRoute,
}

const AdminInventoryRouteWithChildren = AdminInventoryRoute._addFileChildren(
  AdminInventoryRouteChildren,
)

interface AdminLoadoutsRouteChildren {
  AdminLoadoutsContentIdRoute: typeof AdminLoadoutsContentIdRoute
}

const AdminLoadoutsRouteChildren: AdminLoadoutsRouteChildren = {
  AdminLoadoutsContentIdRoute: AdminLoadoutsContentIdRoute,
}

const AdminLoadoutsRouteWithChildren = AdminLoadoutsRoute._addFileChildren(
  AdminLoadoutsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  GuidesRoute: GuidesRouteWithChildren,
  HeroesRoute: HeroesRouteWithChildren,
  InventoryRoute: InventoryRouteWithChildren,
  LoadoutsRoute: LoadoutsRouteWithChildren,
  MissionsGuideRoute: MissionsGuideRoute,
  SchematicsRoute: SchematicsRouteWithChildren,
  VbucksMissionsRoute: VbucksMissionsRoute,
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleArticlesRoute: LocaleArticlesRouteWithChildren,
  LocaleGuidesRoute: LocaleGuidesRouteWithChildren,
  LocaleHeroesRoute: LocaleHeroesRouteWithChildren,
  LocaleInventoryRoute: LocaleInventoryRouteWithChildren,
  LocaleLoadoutsRoute: LocaleLoadoutsRouteWithChildren,
  LocaleMissionsGuideRoute: LocaleMissionsGuideRoute,
  LocaleSchematicsRoute: LocaleSchematicsRouteWithChildren,
  LocaleVbucksMissionsRoute: LocaleVbucksMissionsRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminArticlesRoute: AdminArticlesRouteWithChildren,
  AdminHeroesRoute: AdminHeroesRouteWithChildren,
  AdminInventoryRoute: AdminInventoryRouteWithChildren,
  AdminLoadoutsRoute: AdminLoadoutsRouteWithChildren,
  AdminMediaRoute: AdminMediaRoute,
  AdminPublishingRoute: AdminPublishingRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
