// Source: HawkBucks-Daily-Quotes.md (365 unique quotes).
export const QUOTE_POOL = [
  "Homebase is more than a shelter; it is the promise that we will keep fighting.",
  "Every Storm Shield we defend is another piece of the world we refuse to lose.",
  "When the Husks come, the answer is not fear. It is one more mission, one more stand.",
  "Survivors look to Homebase because hope needs somewhere to stand.",
  "The Storm may cover the horizon, but it has never covered our resolve.",
  "A Commander does not need an easy mission, only a reason to finish it.",
  "Every Hero brings a different strength to the fight, and every strength matters.",
  "The world is still worth saving, even when the Storm says otherwise.",
  "Behind every mission alert is another chance to make tomorrow safer.",
  "Homebase stands because Commanders keep choosing to stand with it.",
  "The Husks can overwhelm a battlefield, but they cannot overwhelm determination.",
  "Storm Shield defenses are built from walls, weapons, and the courage behind them.",
  "Survivors are not just people to protect; they are reminders of what we are fighting for.",
  "Some victories begin with nothing more than a Commander refusing to retreat.",
  "The Storm changes everything except the reason we keep moving forward.",
  "Every mission completed is a small victory against a very large Storm.",
  "Homebase is strongest when every Hero knows their part in the fight.",
  "The Husks bring the darkness; the defenders bring the answer.",
  "A world under siege still has room for heroes.",
  "Storm Shield nights are long, but dawn always gives us another mission.",
  "The best defense is built one brave decision at a time.",
  "Every Survivor rescued is another voice telling the world to keep going.",
  "A Commander measures victory not only in battles won, but in lives protected.",
  "Homebase does not need legends. It needs people willing to show up.",
  "The Storm can test every wall, but it cannot decide what stands behind it.",
  "When the mission begins, hesitation becomes one more enemy to overcome.",
  "Heroes become stronger when they fight for something bigger than themselves.",
  "The Husks may never stop coming, so neither can the defenders.",
  "Every alert is a reminder that the fight for Save the World is still alive.",
  "Homebase is where courage becomes a habit.",
  "The Storm is loud, but determination can be louder.",
  "One mission can change a day; one Commander can change a whole battle.",
  "Survivors carry memories of the world we had and hope for the world ahead.",
  "Every Storm Shield defense is a promise kept.",
  "The hardest missions often reveal the strongest Heroes.",
  "When the Husks surround Homebase, teamwork becomes the strongest weapon.",
  "A quiet Homebase is not an ending; it is preparation for the next fight.",
  "Commanders do not save the world alone; they build teams that can.",
  "Hope survives wherever someone is willing to defend it.",
  "The Storm may have taken much, but it has not taken everything.",
  "Every rescued Survivor is proof that the fight still matters.",
  "Homebase turns scattered survivors into one determined force.",
  "A mission is never just a task when someone's future depends on it.",
  "Heroes are remembered for what they protect, not only what they defeat.",
  "The Storm Shield stands because someone always chooses to defend it.",
  "Even when the odds are impossible, Homebase still needs one more attempt.",
  "The Husks know fear; the defenders know purpose.",
  "Every Commander begins with a simple choice: move forward.",
  "Save the World is a fight measured in courage as much as firepower.",
  "Homebase is built from metal and stone, but held together by hope.",
  "The Storm cannot erase a future that people are still willing to build.",
  "Every Hero has a role, and every role can change the outcome.",
  "Survivors deserve more than survival; they deserve a world worth returning to.",
  "The next mission may be dangerous, but standing still will not save anyone.",
  "Storm Shield defenses are where preparation meets courage.",
  "Homebase is strongest when no one fights alone.",
  "The Husks may surround the walls, but they do not own what is inside.",
  "Every mission alert carries the possibility of another life saved.",
  "Commanders turn chaos into a plan and a plan into a victory.",
  "The Storm tests our defenses, but our choices define them.",
  "A Hero's greatest weapon can be the reason they refuse to quit.",
  "Survivors are the heart of every defense we build.",
  "The world feels smaller when Homebase stands together.",
  "Every wall repaired is another reason to believe tomorrow is possible.",
  "The Husks can break structures; they cannot break a united team.",
  "Save the World begins with defending what still remains.",
  "A Commander sees a crisis and asks where the next defense should stand.",
  "Storm Shield battles are won long before the first Husk arrives.",
  "Every Hero carries a different story into the fight.",
  "Homebase is not just where missions begin; it is why they matter.",
  "The Storm has no mercy, so the defenders must make their own hope.",
  "Survivors remind us that the mission is always bigger than the reward.",
  "One defended objective can become the beginning of a safer world.",
  "Every Husk defeated makes the road ahead a little clearer.",
  "Commanders lead from the front, but victories are built by the whole team.",
  "The strongest Storm Shield is protected by people who believe it is worth protecting.",
  "Hope is a resource Homebase can never afford to run out of.",
  "Every mission is another page in the story of the fight against the Storm.",
  "The Husks may be endless, but so is the resolve of those defending Homebase.",
  "A Hero does not need perfect odds to make a difference.",
  "Survivors give meaning to every weapon, wall, and Storm Shield we defend.",
  "The Storm can darken the sky without deciding what comes next.",
  "Homebase survives because someone always answers the mission alert.",
  "Every Commander learns that courage is often simply refusing to stop.",
  "The world may be broken, but broken is not the same as lost.",
  "Defending Homebase is defending the possibility of a future.",
  "The Husks attack the walls; teamwork protects everything beyond them.",
  "Every rescued Survivor is a victory the Storm cannot take back.",
  "Heroes are strongest when their purpose is shared.",
  "Storm Shield defenses turn uncertainty into something we can face together.",
  "Homebase is a reminder that rebuilding is also a form of victory.",
  "The Storm may arrive every night, but so does another chance to stand.",
  "Every mission completed gives hope another place to grow.",
  "Commanders protect more than objectives; they protect possibilities.",
  "The Husks can claim the darkness, but Homebase belongs to those who keep the lights on.",
  "Every Hero starts with a reason to fight and becomes stronger by remembering it.",
  "Survivors do not need promises of an easy future, only a chance to have one.",
  "Save the World is a collection of choices made when giving up would be easier.",
  "The Storm Shield is more than a structure; it is a line we refuse to surrender.",
  "Homebase turns survival into resistance.",
  "Every mission alert is a call to protect something that still matters.",
  "The Husks are relentless, but so are the people defending the world.",
  "A Commander finds strength not in having no fear, but in moving despite it.",
  "Heroes make difficult missions possible by refusing to fight as strangers.",
  "Survivors are the reason every defense has a purpose.",
  "The Storm can take the horizon, but it cannot take our direction.",
  "Homebase grows stronger with every mission, every defense, and every rescued Survivor.",
  "Every wall has a limit; determination does not have to.",
  "The Husks are a threat, but unity is a force they cannot understand.",
  "Save the World is a promise that the fight is not over yet.",
  "Every Commander carries the weight of the next decision.",
  "Storm Shield defenses teach the same lesson every time: preparation saves lives.",
  "Homebase is where scattered courage becomes collective strength.",
  "The Storm does not care who we are; that is why we must care for one another.",
  "Every Hero adds another answer to the problems the Storm creates.",
  "Survivors are more than passengers on this journey; they are its destination.",
  "A successful mission leaves more than rewards behind; it leaves hope.",
  "The Husks can make the road dangerous, but they cannot make it meaningless.",
  "Every Storm Shield defended is another sunrise earned.",
  "Commanders build teams because no single Hero can carry the whole world.",
  "Homebase stands as long as someone believes it should.",
  "The Storm is a challenge, not a verdict.",
  "Every mission begins with uncertainty and ends with a story worth remembering.",
  "Heroes do not erase the danger; they make facing it possible.",
  "Survivors prove that rebuilding a world begins with protecting its people.",
  "The Husks test the walls, while the mission tests the heart.",
  "Homebase is strongest when every defender knows they matter.",
  "Save the World is not about waiting for the Storm to end; it is about surviving it together.",
  "Every mission alert is an invitation to turn danger into progress.",
  "The Storm Shield is a boundary between what the Husks want and what we will protect.",
  "Commanders turn scattered resources into a reason to keep going.",
  "Heroes bring power to the battlefield, but purpose brings power to the team.",
  "Homebase is proof that even after the world changes, people can still build.",
  "The Husks may destroy what is easy to break; they cannot easily break trust.",
  "Every defense starts with a decision that something is worth saving.",
  "The Storm may be endless, but no single storm lasts forever.",
  "Commanders know that the smallest mission can have the largest meaning.",
  "Survivors give every Storm Shield a reason to stand.",
  "Homebase is not safe because the Storm is weak; it is safe because people defend it.",
  "Every Hero becomes part of something larger when the mission begins.",
  "The Husks are never the whole story; the people standing against them are.",
  "Every mission completed is another step toward rebuilding what the Storm took.",
  "Heroes protect the present so Survivors can have a future.",
  "Homebase is stronger than the Storm because it is built from people, not promises.",
  "Every mission begins with a question and ends with an answer earned in the field.",
  "Save the World is the courage to keep rebuilding after the Storm.",
  "Every Survivor brought home makes the next defense more meaningful.",
  "Commanders lead by remembering who is waiting behind the walls.",
  "The Husks can test our weapons, but they cannot test our reasons.",
  "Every Hero becomes stronger when the mission gives their strength a purpose.",
  "Homebase is the place where the fight for tomorrow becomes today's mission.",
  "The Storm may cover the world, but it cannot cover every spark of hope.",
  "Every defense is stronger when preparation meets trust.",
  "The Husks can threaten the mission, but the team decides its ending.",
  "Save the World is built from ordinary people doing extraordinary things together.",
  "Every Commander knows the next wave will come; that is why the next defense begins now.",
  "Homebase stands because hope has defenders.",
  "Every Survivor deserves a tomorrow, and every mission is a step toward it.",
  "The Storm is never the final word when Homebase still has a voice.",
  "Heroes bring their abilities; teamwork turns them into a force.",
  "The Husks can make the world feel lost, but every rescued Survivor proves it is not.",
  "Every mission alert is a reminder that the fight still has meaning.",
  "Commanders keep the team focused when the Storm tries to take everything else away.",
  "Storm Shield defenses are built to protect more than structures; they protect futures.",
  "Homebase is a place where survival becomes something worth celebrating.",
  "Every Hero has a different path into the fight, but the mission gives them common ground.",
  "The Husks arrive without mercy, and the defenders answer with purpose.",
  "Save the World is a promise renewed every time Homebase opens its doors.",
  "Every mission is one more chance to turn a dangerous world into a safer one.",
  "Survivors are the reason we rebuild instead of retreat.",
  "The Storm can darken every road, but Homebase can still light the way.",
  "Every Commander learns that progress often looks like one completed mission.",
  "The Husks may be the enemy, but giving up would be the real defeat.",
  "Every Storm Shield defense is a declaration that something here is worth saving.",
  "Every mission is another chance to prove that the future is not finished.",
  "Homebase keeps the lights on because someone keeps choosing to defend them.",
  "The Husks can threaten the walls, but they cannot decide what happens after the battle.",
  "Every Survivor is a reminder that rebuilding is the real victory.",
  "Commanders make difficult choices so their teams can keep moving.",
  "Every Hero contributes something the Storm cannot predict: purpose.",
  "Save the World is the courage to protect what the world still has.",
  "Every Storm Shield defense is a line drawn for the sake of tomorrow.",
  "Homebase grows stronger when every mission brings its people closer together.",
  "The Husks are relentless, but so is the hope behind the walls.",
  "Every mission alert is another chance to protect someone who still matters.",
  "Survivors give every defense a future to protect.",
  "Commanders lead because someone has to choose the next direction.",
  "The Storm can make the world feel empty, but Homebase fills it with purpose.",
  "Every Hero has a place in the fight, even when the mission changes.",
  "Save the World is not about avoiding the Storm; it is about refusing to let it decide everything.",
  "Every completed mission is proof that progress can survive the chaos.",
  "Homebase stands because its defenders believe the future is worth the effort.",
  "The Husks can break a wall, but they cannot break a team that rebuilds together.",
  "Every Survivor brought home is another reason to keep the Storm at bay.",
  "Storm Shield defenses are where preparation becomes courage in action.",
  "Commanders turn difficult moments into decisions, and decisions into progress.",
  "Every Hero brings a piece of the solution to every mission.",
  "The Storm may be unpredictable, but the purpose of Homebase remains clear.",
  "Save the World is a story of people who keep choosing to protect one another.",
  "Every mission gives the defenders another opportunity to earn tomorrow.",
  "The Husks may never understand why we fight; we do.",
  "Every Storm Shield defended is another chapter the Storm does not get to write.",
  "Homebase is where courage finds a place to organize.",
  "Every Survivor protected is another reason to keep the defenses standing.",
  "Heroes make the fight brighter simply by showing up.",
  "Commanders keep the mission moving when the Storm tries to stop it.",
  "Save the World is built from small victories that refuse to disappear.",
  "Every defense is a promise that someone will still be here tomorrow.",
  "The Husks can surround Homebase, but they cannot surround its purpose.",
  "Every mission alert is another invitation to protect the future.",
  "The Storm may be powerful, but resilience is built from many small choices.",
  "Every Hero matters when the mission is bigger than any one person.",
  "Survivors are the reason every Commander checks the walls one more time.",
  "Homebase is a reminder that survival becomes stronger when it becomes shared.",
  "Every Storm Shield stands because its defenders refuse to call the fight over.",
  "Save the World is hope with a mission attached to it.",
  "The Husks can make every battle difficult, but they cannot make it pointless.",
  "Every completed mission is another reason to believe Homebase will see another sunrise.",
  "Commanders protect the team by protecting the reason the team exists.",
  "Every Survivor is a future the Storm did not manage to erase.",
  "Heroes bring skill to the fight; courage gives that skill direction.",
  "Homebase does not promise an easy road, only a reason to keep walking it.",
  "Every mission alert is another chance to make the world safer for someone else.",
  "The Storm may never slow down, so the defenders learn to move with purpose.",
  "Every Storm Shield defense proves that preparation can turn fear into confidence.",
  "Save the World is the decision to keep building even when the world is broken.",
  "The Husks can test the walls, but every repaired wall is an answer.",
  "Every Commander who answers the call adds another day to the future.",
  "Homebase is strongest when every Survivor, Hero, and Commander has a place in the plan.",
  "Every mission is a step away from the world the Storm wants and toward the world we choose.",
  "The Storm can threaten the future, but it cannot own the choices that build it.",
  "Every Hero is part of the reason Homebase keeps believing in tomorrow.",
  "Survivors remind us that the goal is not merely to endure, but to rebuild.",
  "Every Husk wave is another test of whether the team can stay together.",
  "Save the World is a fight where every protected life counts.",
  "Homebase is the place where yesterday's losses become tomorrow's preparation.",
  "Every Storm Shield defended is another reason to keep the lights burning.",
  "Commanders lead the mission, but the mission belongs to everyone.",
  "Every Survivor rescued is a small victory that the Storm cannot undo.",
  "The Husks bring chaos; Homebase answers with preparation.",
  "Every mission alert is a signal that hope still has work to do.",
  "Heroes turn preparation into action when the Husks arrive.",
  "Save the World is the belief that rebuilding is worth the fight.",
  "Every Storm Shield defended is another small victory against the chaos outside.",
  "Commanders do not defeat the Storm alone; they build teams that can outlast it.",
  "Every mission completed is another piece of the future secured.",
  "Homebase is where the next chapter begins, no matter how difficult the last one was.",
  "Survivors are proof that even after the Storm, life can continue.",
  "Every Hero brings another reason to believe the fight can be won.",
  "The Husks may keep coming, but Homebase keeps answering.",
  "Every Storm Shield defense is another promise that we are not finished.",
  "Save the World is not a destination; it is the choice to keep defending the road ahead.",
  "Every mission completed gives the future another reason to exist.",
  "Homebase stands today because someone believed it could stand tomorrow.",
  "The Storm can make every horizon uncertain, but every mission gives us a direction.",
  "Every Survivor protected is another reason to call the defense a victory.",
  "Commanders make the hard calls so Heroes can make the difference.",
  "The Husks can challenge our defenses, but they cannot erase the meaning behind them.",
  "Every Storm Shield is a reminder that courage can be built.",
  "Save the World is a fight for more than survival; it is a fight for possibility.",
  "Homebase keeps moving because standing still was never the plan.",
  "Every mission alert is another chance to turn danger into protection.",
  "Every Hero who joins the defense makes the future a little less fragile.",
  "Survivors give the Storm Shield a reason to hold.",
  "The Husks may bring the darkness, but the defenders decide where the light remains.",
  "Every Commander knows the next mission can always change everything.",
  "Save the World survives through every choice to protect someone else.",
  "Homebase is not just a place to return to; it is a reason to return.",
  "Every defense held is another piece of tomorrow secured.",
  "The Storm can test the world, but it cannot decide what kind of people stand in it.",
  "Every Survivor rescued is another reason to keep the next battle worth facing.",
  "Heroes are the sparks that keep Homebase moving when the Storm closes in.",
  "The Husks may be relentless, but the mission can be relentless too.",
  "Every Storm Shield defense is a promise that tomorrow will have defenders.",
  "Save the World is the story of hope refusing to become a memory.",
  "Homebase grows with every mission and survives with every act of courage.",
  "Every Commander starts the mission, but every teammate helps bring it home.",
  "Survivors are the reason every victory matters beyond the battlefield.",
  "The Storm may cover the world in uncertainty, but Homebase answers with purpose.",
  "The Husks can threaten the present, but the mission protects the future.",
  "Every completed mission is a quiet declaration that the Storm has not won.",
  "Save the World is built one defense, one Survivor, and one brave decision at a time.",
  "Homebase stands because its people refuse to let the Storm write the ending.",
  "Every Storm Shield defended is another day earned for the world beyond the walls.",
  "Commanders keep the team moving because every second can protect a future.",
  "The Husks may arrive without warning, but the defenders are always preparing.",
  "Every mission alert is another chance to turn courage into action.",
  "Survivors are the heart of the future Homebase is trying to protect.",
  "Heroes bring strength, Commanders bring direction, and teamwork brings victory.",
  "The Storm can destroy what we built, but it cannot stop us from building again.",
  "Every defense is stronger when everyone remembers who is behind the walls.",
  "Save the World is a promise made to every Survivor who still believes tomorrow is possible.",
  "Homebase is where courage becomes routine and hope becomes practical.",
  "Every mission completed makes the next one a little easier to face.",
  "The Husks can test the team, but the team decides how the story continues.",
  "Every Hero has a reason to fight, and every reason makes Homebase stronger.",
  "Storm Shield defenses are the moments when preparation proves its worth.",
  "Every Survivor brought home is another piece of the future protected from the Storm.",
  "Commanders do not need certainty; they need enough courage for the next step.",
  "Save the World is the choice to protect tomorrow before tomorrow arrives.",
  "Every mission is another chance to leave the world slightly better than we found it.",
  "Homebase is where yesterday's survivors prepare for tomorrow's battles.",
  "The Storm can make the world uncertain, but it makes every act of courage visible.",
  "Every Commander has a mission; every mission has a reason.",
  "Heroes turn impossible situations into problems that can be solved.",
  "Survivors give the fight a face, a voice, and a future.",
  "The Husks are relentless because the Storm is relentless; our defense must be just as persistent.",
  "Homebase is a refuge built by people who refused to abandon the world.",
  "Every mission alert is another opportunity to prove that hope still works.",
  "Save the World is not one final battle; it is every battle we choose to face.",
  "The Storm Shield stands because every defender understands what lies beyond it.",
  "Commanders protect the team by making the next decision before the next wave arrives.",
  "Every Hero matters most when the mission needs them.",
  "Survivors are the reason every defense begins with protecting them.",
  "The Husks may own the roads, but Homebase owns the reason to travel them.",
  "Every completed mission is a quiet victory for everyone still rebuilding.",
  "The Storm can hide the horizon, but Homebase keeps pointing toward it.",
  "Commanders turn difficult missions into shared purpose.",
  "Every Storm Shield is a promise that the world has not been abandoned.",
  "Heroes make the impossible feel like the next objective.",
  "Every Survivor is a reason the fight continues.",
  "The Husks bring pressure; the team brings resilience.",
  "Homebase is strongest when every mission begins with trust.",
  "Every mission alert is a small signal that there is still something worth defending.",
  "The Storm can take the easy path away, leaving courage as the only route forward.",
  "Save the World is a fight for places, people, and the possibility of tomorrow.",
  "Every Commander knows that a team is strongest when every Hero has a purpose.",
  "Storm Shield nights may be long, but they are never wasted.",
  "The Husks can test every defense, but every defense teaches us something new.",
  "Homebase is built one mission at a time and defended one decision at a time.",
  "Every Survivor brought home is another piece of the future protected.",
  "Heroes are not measured by perfect victories, but by the missions they refuse to abandon.",
  "The Storm does not ask whether we are ready; Homebase teaches us to become ready.",
  "Every mission gives the defenders another reason to believe in tomorrow.",
  "Commanders make the first move, but the whole team carries it forward.",
  "The Husks may surround the objective, but they cannot surround a united team.",
  "Save the World is a story written by every Commander who keeps answering the call.",
  "Every Storm Shield defense turns preparation into protection.",
  "Homebase is where hope gets organized.",
  "Survivors remind us that every successful defense has a human reason behind it.",
  "The Storm may never apologize, so we never wait for permission to rebuild.",
  "Every Hero has a moment when their strength becomes someone else's hope.",
  "The Husks are a reminder that peace must be defended.",
  "Commanders do not wait for perfect conditions; they prepare with what they have.",
  "Every mission alert can become a turning point when the team answers together.",
  "Homebase survives because its defenders make survival a shared responsibility.",
  "The Storm can scatter a world, but it cannot scatter people who choose to stand together.",
  "Every Survivor rescued is another reason to reinforce the walls again.",
  "Heroes turn pressure into action and action into progress.",
  "Save the World is the belief that every defense can become a beginning.",
  "Homebase keeps its doors open because the fight still has a purpose.",
  "Every mission alert is another signal that someone still needs a defender.",
  "The Husks can surround the walls, but they cannot surround the hope behind them.",
  "Every Storm Shield stands as a quiet refusal to surrender.",
  "Heroes make difficult missions possible by bringing different strengths together.",
  "Survivors are the reason the battle is never only about winning.",
  "The Storm may be endless, but every day we defend is still ours.",
  "Every Commander learns that the strongest answer is often simply: keep going.",
  "Save the World is a collection of small choices that become a future.",
  "Homebase is strongest when its people protect one another as fiercely as they protect its walls.",
  "Every mission gives us another opportunity to prove the future is worth the fight.",
  "The Husks can take ground, but they cannot take our purpose.",
  "Every Hero is a reminder that courage can come in many forms.",
  "Storm Shield defenses are built from preparation, teamwork, and the refusal to give up.",
  "Every Survivor protected is another reason to keep Homebase standing.",
];

if (
  QUOTE_POOL.length !== 365 ||
  new Set(QUOTE_POOL).size !== QUOTE_POOL.length
) {
  throw new Error("Daily quote pool must contain exactly 365 unique quotes");
}
