import { en, type PublicStrings } from "./public-strings-base";
function withEn(p: Partial<PublicStrings>): PublicStrings {
  return { ...en, ...p };
}
export const pt: PublicStrings = withEn({
  heroesTitle: "Heróis",
  loadoutsTitle: "Composições",
  inventoryTitle: "Inventário",
  inventoryIntro:
    "Explore todos os esquemas publicados. Filtre por armas ou armadilhas, pesquise por nome.",
  typeLabel: "Tipo",
  typeAll: "Todos",
  typeWeapon: "Armas",
  typeTrap: "Armadilhas",
  perksLabel: "Vantagens",
  perkSlotLabel: "Espaço",
  backToInventory: "Voltar ao inventário",
  weaponLabel: "Arma",
  trapLabel: "Armadilha",
  subtypeLabel: "Subtipo",
  searchPlaceholder: "Pesquisar por nome…",
  classLabel: "Classe",
  classAll: "Todos",
  sortLabel: "Ordenar",
  sortEditorial: "Destaques",
  sortPopularity: "Popularidade",
  sortName: "Nome",
  emptyTitle: "Sem resultados",
  loading: "Carregando…",
  retry: "Tentar novamente",
  viewDetails: "Ver detalhes",
  openPreview: "Visualização rápida",
  close: "Fechar",
  commander: "Comandante",
  supportTeam: "Equipe de suporte",
  supportSlot: "Espaço de suporte",
  emptySlot: "Espaço vazio",
  abilities: "Habilidades",
  relatedLoadouts: "Composições relacionadas",
  backToHeroes: "Voltar aos heróis",
  backToLoadouts: "Voltar às composições",
  categoryLabel: "Categoria",
});
export const zh: PublicStrings = withEn({
  heroesTitle: "英雄",
  loadoutsTitle: "阵容",
  inventoryTitle: "物品库",
  inventoryIntro: "浏览所有已发布的蓝图。按武器或陷阱筛选，按名称搜索。",
  typeLabel: "类型",
  typeAll: "全部",
  typeWeapon: "武器",
  typeTrap: "陷阱",
  perksLabel: "特长",
  perkSlotLabel: "槽位",
  backToInventory: "返回物品库",
  weaponLabel: "武器",
  trapLabel: "陷阱",
  subtypeLabel: "子类型",
  searchPlaceholder: "按名称搜索…",
  classLabel: "职业",
  classAll: "全部",
  sortLabel: "排序",
  sortEditorial: "推荐",
  sortPopularity: "人气",
  sortName: "名称",
  emptyTitle: "没有结果",
  loading: "加载中…",
  retry: "重试",
  viewDetails: "查看详情",
  openPreview: "快速预览",
  close: "关闭",
  commander: "指挥官",
  supportTeam: "支援小队",
  supportSlot: "支援槽位",
  emptySlot: "空槽位",
  abilities: "技能",
  relatedLoadouts: "相关阵容",
  backToHeroes: "返回英雄列表",
  backToLoadouts: "返回阵容列表",
  categoryLabel: "分类",
});
