import { en, type PublicStrings } from "./public-strings-base";
function withEn(p: Partial<PublicStrings>): PublicStrings {
  return { ...en, ...p };
}
export const es: PublicStrings = withEn({
  heroesTitle: "Héroes",
  loadoutsTitle: "Equipos",
  inventoryTitle: "Inventario",
  inventoryIntro:
    "Explora todos los esquemas publicados. Filtra por armas o trampas, busca por nombre y abre cualquier tarjeta.",
  typeLabel: "Tipo",
  typeAll: "Todos",
  typeWeapon: "Armas",
  typeTrap: "Trampas",
  perksLabel: "Ventajas",
  perkSlotLabel: "Espacio",
  backToInventory: "Volver al inventario",
  weaponLabel: "Arma",
  trapLabel: "Trampa",
  subtypeLabel: "Subtipo",
  searchPlaceholder: "Buscar por nombre…",
  classLabel: "Clase",
  classAll: "Todos",
  sortLabel: "Ordenar",
  sortEditorial: "Destacados",
  sortPopularity: "Popularidad",
  sortName: "Nombre",
  emptyTitle: "Sin resultados",
  loading: "Cargando…",
  retry: "Reintentar",
  viewDetails: "Ver detalles",
  openPreview: "Vista rápida",
  close: "Cerrar",
  commander: "Comandante",
  supportTeam: "Equipo de apoyo",
  supportSlot: "Espacio de apoyo",
  emptySlot: "Espacio vacío",
  abilities: "Habilidades",
  relatedLoadouts: "Equipos relacionados",
  backToHeroes: "Volver a Héroes",
  backToLoadouts: "Volver a Equipos",
  categoryLabel: "Categoría",
});
export const fr: PublicStrings = withEn({
  heroesTitle: "Héros",
  loadoutsTitle: "Compositions",
  inventoryTitle: "Inventaire",
  inventoryIntro:
    "Parcourez tous les schémas publiés. Filtrez par armes ou pièges, recherchez par nom.",
  typeLabel: "Type",
  typeAll: "Tous",
  typeWeapon: "Armes",
  typeTrap: "Pièges",
  perksLabel: "Atouts",
  perkSlotLabel: "Emplacement",
  backToInventory: "Retour à l'inventaire",
  weaponLabel: "Arme",
  trapLabel: "Piège",
  subtypeLabel: "Sous-type",
  searchPlaceholder: "Rechercher par nom…",
  classLabel: "Classe",
  classAll: "Tous",
  sortLabel: "Trier",
  sortEditorial: "En vedette",
  sortPopularity: "Popularité",
  sortName: "Nom",
  emptyTitle: "Aucun résultat",
  loading: "Chargement…",
  retry: "Réessayer",
  viewDetails: "Voir les détails",
  openPreview: "Aperçu",
  close: "Fermer",
  commander: "Commandant",
  supportTeam: "Équipe de soutien",
  supportSlot: "Emplacement de soutien",
  emptySlot: "Emplacement vide",
  abilities: "Capacités",
  relatedLoadouts: "Compositions liées",
  backToHeroes: "Retour aux héros",
  backToLoadouts: "Retour aux compositions",
  categoryLabel: "Catégorie",
});
export const ru: PublicStrings = withEn({
  heroesTitle: "Герои",
  loadoutsTitle: "Сборки",
  inventoryTitle: "Инвентарь",
  inventoryIntro: "Все опубликованные чертежи. Фильтруйте по оружию или ловушкам, ищите по имени.",
  typeLabel: "Тип",
  typeAll: "Все",
  typeWeapon: "Оружие",
  typeTrap: "Ловушки",
  perksLabel: "Перки",
  perkSlotLabel: "Слот",
  backToInventory: "Назад к инвентарю",
  weaponLabel: "Оружие",
  trapLabel: "Ловушка",
  subtypeLabel: "Подтип",
  searchPlaceholder: "Поиск по имени…",
  classLabel: "Класс",
  classAll: "Все",
  sortLabel: "Сортировка",
  sortEditorial: "Рекомендуемые",
  sortPopularity: "Популярность",
  sortName: "Имя",
  emptyTitle: "Ничего не найдено",
  loading: "Загрузка…",
  retry: "Повторить",
  viewDetails: "Подробнее",
  openPreview: "Быстрый просмотр",
  close: "Закрыть",
  commander: "Командир",
  supportTeam: "Группа поддержки",
  supportSlot: "Слот поддержки",
  emptySlot: "Пустой слот",
  abilities: "Способности",
  relatedLoadouts: "Связанные сборки",
  backToHeroes: "Назад к героям",
  backToLoadouts: "Назад к сборкам",
  categoryLabel: "Категория",
});
export const de: PublicStrings = withEn({
  heroesTitle: "Helden",
  loadoutsTitle: "Loadouts",
  inventoryTitle: "Inventar",
  inventoryIntro:
    "Alle veröffentlichten Baupläne. Nach Waffen oder Fallen filtern, nach Namen suchen.",
  typeLabel: "Typ",
  typeAll: "Alle",
  typeWeapon: "Waffen",
  typeTrap: "Fallen",
  perksLabel: "Perks",
  perkSlotLabel: "Slot",
  backToInventory: "Zurück zum Inventar",
  weaponLabel: "Waffe",
  trapLabel: "Falle",
  subtypeLabel: "Untertyp",
  searchPlaceholder: "Nach Namen suchen…",
  classLabel: "Klasse",
  classAll: "Alle",
  sortLabel: "Sortierung",
  sortEditorial: "Empfohlen",
  sortPopularity: "Beliebtheit",
  sortName: "Name",
  emptyTitle: "Keine Ergebnisse",
  loading: "Wird geladen…",
  retry: "Wiederholen",
  viewDetails: "Details ansehen",
  openPreview: "Schnellansicht",
  close: "Schließen",
  commander: "Commander",
  supportTeam: "Support-Team",
  supportSlot: "Support-Slot",
  emptySlot: "Leerer Slot",
  abilities: "Fähigkeiten",
  relatedLoadouts: "Ähnliche Loadouts",
  backToHeroes: "Zurück zu Helden",
  backToLoadouts: "Zurück zu Loadouts",
  categoryLabel: "Kategorie",
});
