import { en, type PublicStrings } from "./public-strings-base";
function withEn(p: Partial<PublicStrings>): PublicStrings {
  return { ...en, ...p };
}
export const arSA: PublicStrings = withEn({
  heroesTitle: "الأبطال",
  loadoutsTitle: "التشكيلات",
  inventoryTitle: "المخزون",
  inventoryIntro: "تصفح كل المخططات المنشورة. صفِّ حسب الأسلحة أو الفخاخ، وابحث بالاسم.",
  typeLabel: "النوع",
  typeAll: "الكل",
  typeWeapon: "الأسلحة",
  typeTrap: "الفخاخ",
  perksLabel: "الميزات",
  perkSlotLabel: "الخانة",
  backToInventory: "عودة إلى المخزون",
  weaponLabel: "سلاح",
  trapLabel: "فخ",
  subtypeLabel: "النوع الفرعي",
  searchPlaceholder: "ابحث بالاسم…",
  classLabel: "الفئة",
  classAll: "الكل",
  sortLabel: "الترتيب",
  sortEditorial: "المميز",
  sortPopularity: "الشعبية",
  sortName: "الاسم",
  emptyTitle: "لا توجد نتائج",
  loading: "جارٍ التحميل…",
  retry: "إعادة المحاولة",
  viewDetails: "عرض التفاصيل",
  openPreview: "معاينة سريعة",
  close: "إغلاق",
  commander: "القائد",
  supportTeam: "فريق الدعم",
  supportSlot: "خانة الدعم",
  emptySlot: "خانة فارغة",
  abilities: "القدرات",
  relatedLoadouts: "تشكيلات مرتبطة",
  backToHeroes: "عودة إلى الأبطال",
  backToLoadouts: "عودة إلى التشكيلات",
  categoryLabel: "التصنيف",
});
export const faIR: PublicStrings = withEn({
  heroesTitle: "هیروها",
  loadoutsTitle: "ترکیب‌ها",
  inventoryTitle: "موجودی",
  inventoryIntro:
    "همه نقشه‌های منتشرشده را مرور کنید. بر اساس سلاح یا تله فیلتر کنید، با نام جستجو کنید.",
  typeLabel: "نوع",
  typeAll: "همه",
  typeWeapon: "سلاح‌ها",
  typeTrap: "تله‌ها",
  perksLabel: "پرک‌ها",
  perkSlotLabel: "جایگاه",
  backToInventory: "بازگشت به موجودی",
  weaponLabel: "سلاح",
  trapLabel: "تله",
  subtypeLabel: "زیرنوع",
  searchPlaceholder: "جستجو با نام…",
  classLabel: "کلاس",
  classAll: "همه",
  sortLabel: "مرتب‌سازی",
  sortEditorial: "پیشنهادی",
  sortPopularity: "محبوبیت",
  sortName: "نام",
  emptyTitle: "نتیجه‌ای نیست",
  loading: "در حال بارگذاری…",
  retry: "تلاش مجدد",
  viewDetails: "مشاهده جزئیات",
  openPreview: "پیش‌نمایش سریع",
  close: "بستن",
  commander: "فرمانده",
  supportTeam: "تیم پشتیبانی",
  supportSlot: "جایگاه پشتیبانی",
  emptySlot: "جایگاه خالی",
  abilities: "توانایی‌ها",
  relatedLoadouts: "ترکیب‌های مرتبط",
  backToHeroes: "بازگشت به هیروها",
  backToLoadouts: "بازگشت به ترکیب‌ها",
  categoryLabel: "دسته‌بندی",
});
export const CLASS_LABELS: Record<string, Record<string, string>> = {
  en: { soldier: "Soldier", constructor: "Constructor", ninja: "Ninja", outlander: "Outlander" },
  es: { soldier: "Soldado", constructor: "Constructor", ninja: "Ninja", outlander: "Trotamundos" },
  fr: { soldier: "Soldat", constructor: "Constructeur", ninja: "Ninja", outlander: "Éclaireur" },
  ru: {
    soldier: "Солдат",
    constructor: "Конструктор",
    ninja: "Ниндзя",
    outlander: "Путешественник",
  },
  de: { soldier: "Soldat", constructor: "Konstrukteur", ninja: "Ninja", outlander: "Outlander" },
  pt: { soldier: "Soldado", constructor: "Construtor", ninja: "Ninja", outlander: "Forasteiro" },
  zh: { soldier: "士兵", constructor: "建筑师", ninja: "忍者", outlander: "探路者" },
  "ar-SA": { soldier: "جندي", constructor: "بنّاء", ninja: "نينجا", outlander: "مستكشف" },
  "fa-IR": { soldier: "سرباز", constructor: "سازنده", ninja: "نینجا", outlander: "دیده‌بان" },
};
export function heroClassLabel(locale: string, heroClass: string): string {
  return CLASS_LABELS[locale]?.[heroClass] ?? CLASS_LABELS["en"]?.[heroClass] ?? heroClass;
}
