import { en, type PublicStrings } from "./public-strings-base";
function withEn(p: Partial<PublicStrings>): PublicStrings {
  return { ...en, ...p };
}
export const arSA: PublicStrings = withEn({
  heroesTitle: "الأبطال",
  heroesIntro: "استكشف أبطال Save the World: فئاتهم وندرهم وقدراتهم وميزاتهم.",
  loadoutsTitle: "التشكيلات",
  loadoutsIntro:
    "استكشف تشكيلات أبطال مبنية حول القادة وأبطال الدعم وميزات الفريق والعُدد الموصى بها.",
  schematicsTitle: "المخططات",
  schematicsIntro:
    "تصفّح الأسلحة والفخاخ، وقارن أنواعها وميزاتها، واعثر على العُدد التي تناسب تشكيلتك.",
  guidesTitle: "الأدلة",
  guidesIntro: "أدلة ومقارنات وتشكيلات ونصائح عملية لـ Save the World.",
  typeLabel: "النوع",
  typeAll: "الكل",
  typeWeapon: "الأسلحة",
  typeTrap: "الفخاخ",
  perksLabel: "الميزات",
  perkSlotLabel: "الخانة",
  backToSchematics: "عودة إلى المخططات",
  weaponLabel: "سلاح",
  trapLabel: "فخ",
  subtypeLabel: "النوع الفرعي",
  placementLabel: "موضع التركيب",
  searchLabel: "بحث",
  searchPlaceholder: "ابحث بالاسم…",
  classLabel: "الفئة",
  classAll: "الكل",
  sortLabel: "الترتيب",
  sortEditorial: "المميز",
  sortPopularity: "الشعبية",
  sortName: "الاسم",
  sortRecent: "آخر تحديث",
  rarityLabel: "الندرة",
  rarityLegendary: "أسطوري",
  rarityMythic: "خرافي",
  filtersLabel: "المرشحات",
  clearFilters: "مسح المرشحات",
  resultHeroes: "{count} أبطال",
  resultSchematics: "{count} مخططات",
  resultLoadouts: "{count} تشكيلات",
  resultGuides: "{count} أدلة",
  emptyHeroesTitle: "لم يتم العثور على أبطال",
  emptyHeroesDesc: "جرّب اسمًا أو فئة أو ندرة أخرى.",
  emptySchematicsTitle: "لم يتم العثور على مخططات",
  emptySchematicsDesc: "جرّب بحثًا آخر أو عدّل المرشحات.",
  emptyLoadoutsTitle: "لم يتم العثور على تشكيلات",
  emptyLoadoutsDesc: "جرّب بحثًا آخر أو امسح المرشحات.",
  emptyGuidesTitle: "لم يتم العثور على أدلة",
  emptyGuidesDesc: "جرّب بحثًا آخر أو تصفّح موضوعًا آخر.",
  featuredGuide: "دليل مميز",
  latestGuides: "أحدث الأدلة",
  readGuide: "اقرأ الدليل",
  topicsLabel: "المواضيع",
  topicAll: "كل المواضيع",
  loading: "جارٍ التحميل…",
  loadError: "تعذّر تحميل المحتوى. حاول مرة أخرى.",
  retry: "إعادة المحاولة",
  viewDetails: "عرض التفاصيل",
  openPreview: "معاينة سريعة",
  close: "إغلاق",
  commander: "القائد",
  supportTeam: "فريق الدعم",
  supportSlot: "خانة الدعم",
  emptySlot: "خانة فارغة",
  abilities: "القدرات",
  relatedLoadouts: "تشكيلات مرتبطة",
  backToHeroes: "عودة إلى الأبطال",
  backToLoadouts: "عودة إلى التشكيلات",
  categoryLabel: "التصنيف",
  classNameLabel: "الفئة",
});
export const faIR: PublicStrings = withEn({
  heroesTitle: "هیروها",
  heroesIntro: "هیروهای Save the World را کاوش کنید: کلاس‌ها، کمیابی، توانایی‌ها و پرک‌ها.",
  loadoutsTitle: "ترکیب‌ها",
  loadoutsIntro:
    "ترکیب‌های آماده هیرو بر پایه فرمانده، هیروهای پشتیبان، پرک‌های تیمی و تجهیزات پیشنهادی.",
  schematicsTitle: "نقشه‌ها",
  schematicsIntro:
    "سلاح‌ها و تله‌ها را مرور کنید، نوع و پرک‌هایشان را مقایسه کنید و تجهیزات مناسب ترکیب خود را بیابید.",
  guidesTitle: "راهنماها",
  guidesIntro: "راهنماها، مقایسه‌ها، ترکیب‌ها و نکته‌های کاربردی برای Save the World.",
  typeLabel: "نوع",
  typeAll: "همه",
  typeWeapon: "سلاح‌ها",
  typeTrap: "تله‌ها",
  perksLabel: "پرک‌ها",
  perkSlotLabel: "جایگاه",
  backToSchematics: "بازگشت به نقشه‌ها",
  weaponLabel: "سلاح",
  trapLabel: "تله",
  subtypeLabel: "زیرنوع",
  placementLabel: "محل نصب",
  searchLabel: "جستجو",
  searchPlaceholder: "جستجو با نام…",
  classLabel: "کلاس",
  classAll: "همه",
  sortLabel: "مرتب‌سازی",
  sortEditorial: "پیشنهادی",
  sortPopularity: "محبوبیت",
  sortName: "نام",
  sortRecent: "به‌روزرسانی اخیر",
  rarityLabel: "کمیابی",
  rarityLegendary: "افسانه‌ای",
  rarityMythic: "اسطوره‌ای",
  filtersLabel: "فیلترها",
  clearFilters: "پاک کردن فیلترها",
  resultHeroes: "{count} هیرو",
  resultSchematics: "{count} نقشه",
  resultLoadouts: "{count} ترکیب",
  resultGuides: "{count} راهنما",
  emptyHeroesTitle: "هیرویی یافت نشد",
  emptyHeroesDesc: "نام، کلاس یا کمیابی دیگری را امتحان کنید.",
  emptySchematicsTitle: "نقشه‌ای یافت نشد",
  emptySchematicsDesc: "جستجوی دیگری را امتحان کنید یا فیلترها را تغییر دهید.",
  emptyLoadoutsTitle: "ترکیبی یافت نشد",
  emptyLoadoutsDesc: "جستجوی دیگری را امتحان کنید یا فیلترها را پاک کنید.",
  emptyGuidesTitle: "راهنمایی یافت نشد",
  emptyGuidesDesc: "جستجوی دیگری را امتحان کنید یا موضوع دیگری را ببینید.",
  featuredGuide: "راهنمای ویژه",
  latestGuides: "تازه‌ترین راهنماها",
  readGuide: "خواندن راهنما",
  topicsLabel: "موضوع‌ها",
  topicAll: "همه موضوع‌ها",
  loading: "در حال بارگذاری…",
  loadError: "بارگذاری محتوا ممکن نشد. دوباره تلاش کنید.",
  retry: "تلاش مجدد",
  viewDetails: "مشاهده جزئیات",
  openPreview: "پیش‌نمایش سریع",
  close: "بستن",
  commander: "فرمانده",
  supportTeam: "تیم پشتیبانی",
  supportSlot: "جایگاه پشتیبانی",
  emptySlot: "جایگاه خالی",
  abilities: "توانایی‌ها",
  relatedLoadouts: "ترکیب‌های مرتبط",
  backToHeroes: "بازگشت به هیروها",
  backToLoadouts: "بازگشت به ترکیب‌ها",
  categoryLabel: "دسته‌بندی",
  classNameLabel: "کلاس",
});
export const CLASS_LABELS: Record<string, Record<string, string>> = {
  en: { soldier: "Soldier", constructor: "Constructor", ninja: "Ninja", outlander: "Outlander" },
  es: { soldier: "Soldado", constructor: "Constructor", ninja: "Ninja", outlander: "Trotamundos" },
  fr: { soldier: "Soldat", constructor: "Constructeur", ninja: "Ninja", outlander: "Éclaireur" },
  ru: {
    soldier: "Солдат",
    constructor: "Конструктор",
    ninja: "Ниндзя",
    outlander: "Путешественник",
  },
  de: { soldier: "Soldat", constructor: "Konstrukteur", ninja: "Ninja", outlander: "Outlander" },
  pt: { soldier: "Soldado", constructor: "Construtor", ninja: "Ninja", outlander: "Forasteiro" },
  zh: { soldier: "士兵", constructor: "建筑师", ninja: "忍者", outlander: "探路者" },
  "ar-SA": { soldier: "جندي", constructor: "بنّاء", ninja: "نينجا", outlander: "مستكشف" },
  "fa-IR": { soldier: "سرباز", constructor: "سازنده", ninja: "نینجا", outlander: "دیده‌بان" },
};
export function heroClassLabel(locale: string, heroClass: string): string {
  return CLASS_LABELS[locale]?.[heroClass] ?? CLASS_LABELS["en"]?.[heroClass] ?? heroClass;
}
