import { en, type PublicStrings } from "./public-strings-base";
function withEn(p: Partial<PublicStrings>): PublicStrings {
  return { ...en, ...p };
}
export const es: PublicStrings = withEn({
  heroesTitle: "Héroes",
  heroesIntro: "Explora los Héroes de Save the World: sus clases, rarezas, habilidades y ventajas.",
  loadoutsTitle: "Equipos",
  loadoutsIntro:
    "Explora equipos de Héroes creados en torno a Comandantes, Héroes de apoyo, Ventajas de equipo y equipo recomendado.",
  schematicsTitle: "Esquemas",
  schematicsIntro:
    "Explora armas y trampas, compara sus tipos y ventajas, y encuentra el equipo que encaje en tu configuración.",
  guidesTitle: "Guías",
  guidesIntro: "Guías, comparativas, configuraciones y consejos prácticos para Save the World.",
  typeLabel: "Tipo",
  typeAll: "Todos",
  typeWeapon: "Armas",
  typeTrap: "Trampas",
  perksLabel: "Ventajas",
  perkSlotLabel: "Espacio",
  backToSchematics: "Volver a Esquemas",
  weaponLabel: "Arma",
  trapLabel: "Trampa",
  subtypeLabel: "Subtipo",
  placementLabel: "Colocación",
  searchLabel: "Buscar",
  searchPlaceholder: "Buscar por nombre…",
  classLabel: "Clase",
  classAll: "Todos",
  sortLabel: "Ordenar",
  sortEditorial: "Destacados",
  sortPopularity: "Popularidad",
  sortName: "Nombre",
  sortRecent: "Actualizado recientemente",
  rarityLabel: "Rareza",
  rarityLegendary: "Legendario",
  rarityMythic: "Mítico",
  filtersLabel: "Filtros",
  clearFilters: "Quitar filtros",
  resultHeroes: "{count} Héroes",
  resultSchematics: "{count} Esquemas",
  resultLoadouts: "{count} Equipos",
  resultGuides: "{count} Guías",
  emptyHeroesTitle: "No se encontraron Héroes",
  emptyHeroesDesc: "Prueba con otro nombre, clase o rareza.",
  emptySchematicsTitle: "No se encontraron Esquemas",
  emptySchematicsDesc: "Prueba otra búsqueda o ajusta los filtros.",
  emptyLoadoutsTitle: "No se encontraron Equipos",
  emptyLoadoutsDesc: "Prueba otra búsqueda o quita los filtros.",
  emptyGuidesTitle: "No se encontraron Guías",
  emptyGuidesDesc: "Prueba otra búsqueda o explora otro tema.",
  featuredGuide: "Guía destacada",
  latestGuides: "Últimas guías",
  readGuide: "Leer guía",
  topicsLabel: "Temas",
  topicAll: "Todos los temas",
  loading: "Cargando…",
  loadError: "No se pudo cargar el contenido. Inténtalo de nuevo.",
  retry: "Reintentar",
  viewDetails: "Ver detalles",
  openPreview: "Vista rápida",
  close: "Cerrar",
  commander: "Comandante",
  supportTeam: "Equipo de apoyo",
  supportSlot: "Espacio de apoyo",
  emptySlot: "Espacio vacío",
  abilities: "Habilidades",
  relatedLoadouts: "Equipos relacionados",
  backToHeroes: "Volver a Héroes",
  backToLoadouts: "Volver a Equipos",
  categoryLabel: "Categoría",
  classNameLabel: "Clase",
});
export const fr: PublicStrings = withEn({
  heroesTitle: "Héros",
  heroesIntro:
    "Explorez les Héros de Save the World : leurs classes, raretés, capacités et atouts.",
  loadoutsTitle: "Compositions",
  loadoutsIntro:
    "Explorez des compositions de Héros construites autour de Commandants, Héros de soutien, Atouts d'équipe et équipement recommandé.",
  schematicsTitle: "Schémas",
  schematicsIntro:
    "Parcourez les armes et les pièges, comparez leurs types et leurs atouts, et trouvez l'équipement adapté à votre composition.",
  guidesTitle: "Guides",
  guidesIntro: "Guides, comparatifs, compositions et conseils pratiques pour Save the World.",
  typeLabel: "Type",
  typeAll: "Tous",
  typeWeapon: "Armes",
  typeTrap: "Pièges",
  perksLabel: "Atouts",
  perkSlotLabel: "Emplacement",
  backToSchematics: "Retour aux Schémas",
  weaponLabel: "Arme",
  trapLabel: "Piège",
  subtypeLabel: "Sous-type",
  placementLabel: "Placement",
  searchLabel: "Rechercher",
  searchPlaceholder: "Rechercher par nom…",
  classLabel: "Classe",
  classAll: "Tous",
  sortLabel: "Trier",
  sortEditorial: "En vedette",
  sortPopularity: "Popularité",
  sortName: "Nom",
  sortRecent: "Mis à jour",
  rarityLabel: "Rareté",
  rarityLegendary: "Légendaire",
  rarityMythic: "Mythique",
  filtersLabel: "Filtres",
  clearFilters: "Effacer les filtres",
  resultHeroes: "{count} Héros",
  resultSchematics: "{count} Schémas",
  resultLoadouts: "{count} Compositions",
  resultGuides: "{count} Guides",
  emptyHeroesTitle: "Aucun Héros trouvé",
  emptyHeroesDesc: "Essayez un autre nom, une autre classe ou une autre rareté.",
  emptySchematicsTitle: "Aucun Schéma trouvé",
  emptySchematicsDesc: "Essayez une autre recherche ou ajustez vos filtres.",
  emptyLoadoutsTitle: "Aucune Composition trouvée",
  emptyLoadoutsDesc: "Essayez une autre recherche ou effacez vos filtres.",
  emptyGuidesTitle: "Aucun Guide trouvé",
  emptyGuidesDesc: "Essayez une autre recherche ou parcourez un autre thème.",
  featuredGuide: "Guide en vedette",
  latestGuides: "Derniers guides",
  readGuide: "Lire le guide",
  topicsLabel: "Thèmes",
  topicAll: "Tous les thèmes",
  loading: "Chargement…",
  loadError: "Impossible de charger le contenu. Veuillez réessayer.",
  retry: "Réessayer",
  viewDetails: "Voir les détails",
  openPreview: "Aperçu",
  close: "Fermer",
  commander: "Commandant",
  supportTeam: "Équipe de soutien",
  supportSlot: "Emplacement de soutien",
  emptySlot: "Emplacement vide",
  abilities: "Capacités",
  relatedLoadouts: "Compositions liées",
  backToHeroes: "Retour aux héros",
  backToLoadouts: "Retour aux compositions",
  categoryLabel: "Catégorie",
  classNameLabel: "Classe",
});
export const ru: PublicStrings = withEn({
  heroesTitle: "Герои",
  heroesIntro: "Изучайте героев Save the World: их классы, редкость, способности и перки.",
  loadoutsTitle: "Сборки",
  loadoutsIntro:
    "Готовые сборки героев: командир, герои поддержки, командные перки и рекомендуемое снаряжение.",
  schematicsTitle: "Чертежи",
  schematicsIntro:
    "Просматривайте оружие и ловушки, сравнивайте их типы и перки и находите снаряжение под свою сборку.",
  guidesTitle: "Гайды",
  guidesIntro: "Гайды, сравнения, сборки и практические советы по Save the World.",
  typeLabel: "Тип",
  typeAll: "Все",
  typeWeapon: "Оружие",
  typeTrap: "Ловушки",
  perksLabel: "Перки",
  perkSlotLabel: "Слот",
  backToSchematics: "Назад к чертежам",
  weaponLabel: "Оружие",
  trapLabel: "Ловушка",
  subtypeLabel: "Подтип",
  placementLabel: "Размещение",
  searchLabel: "Поиск",
  searchPlaceholder: "Поиск по имени…",
  classLabel: "Класс",
  classAll: "Все",
  sortLabel: "Сортировка",
  sortEditorial: "Рекомендуемые",
  sortPopularity: "Популярность",
  sortName: "Имя",
  sortRecent: "Недавно обновлённые",
  rarityLabel: "Редкость",
  rarityLegendary: "Легендарный",
  rarityMythic: "Мифический",
  filtersLabel: "Фильтры",
  clearFilters: "Сбросить фильтры",
  resultHeroes: "{count} героев",
  resultSchematics: "{count} чертежей",
  resultLoadouts: "{count} сборок",
  resultGuides: "{count} гайдов",
  emptyHeroesTitle: "Герои не найдены",
  emptyHeroesDesc: "Попробуйте другое имя, класс или редкость.",
  emptySchematicsTitle: "Чертежи не найдены",
  emptySchematicsDesc: "Попробуйте другой запрос или измените фильтры.",
  emptyLoadoutsTitle: "Сборки не найдены",
  emptyLoadoutsDesc: "Попробуйте другой запрос или сбросьте фильтры.",
  emptyGuidesTitle: "Гайды не найдены",
  emptyGuidesDesc: "Попробуйте другой запрос или выберите другую тему.",
  featuredGuide: "Избранный гайд",
  latestGuides: "Последние гайды",
  readGuide: "Читать гайд",
  topicsLabel: "Темы",
  topicAll: "Все темы",
  loading: "Загрузка…",
  loadError: "Не удалось загрузить содержимое. Попробуйте ещё раз.",
  retry: "Повторить",
  viewDetails: "Подробнее",
  openPreview: "Быстрый просмотр",
  close: "Закрыть",
  commander: "Командир",
  supportTeam: "Группа поддержки",
  supportSlot: "Слот поддержки",
  emptySlot: "Пустой слот",
  abilities: "Способности",
  relatedLoadouts: "Связанные сборки",
  backToHeroes: "Назад к героям",
  backToLoadouts: "Назад к сборкам",
  categoryLabel: "Категория",
  classNameLabel: "Класс",
});
export const de: PublicStrings = withEn({
  heroesTitle: "Helden",
  heroesIntro:
    "Entdecke die Helden von Save the World: Klassen, Seltenheiten, Fähigkeiten und Perks.",
  loadoutsTitle: "Loadouts",
  loadoutsIntro:
    "Entdecke Hero-Loadouts rund um Commander, Support-Helden, Team-Perks und empfohlene Ausrüstung.",
  schematicsTitle: "Baupläne",
  schematicsIntro:
    "Durchsuche Waffen und Fallen, vergleiche Typen und Perks und finde die Ausrüstung, die zu deinem Loadout passt.",
  guidesTitle: "Guides",
  guidesIntro: "Guides, Vergleiche, Builds und praktische Tipps für Save the World.",
  typeLabel: "Typ",
  typeAll: "Alle",
  typeWeapon: "Waffen",
  typeTrap: "Fallen",
  perksLabel: "Perks",
  perkSlotLabel: "Slot",
  backToSchematics: "Zurück zu Bauplänen",
  weaponLabel: "Waffe",
  trapLabel: "Falle",
  subtypeLabel: "Untertyp",
  placementLabel: "Platzierung",
  searchLabel: "Suche",
  searchPlaceholder: "Nach Namen suchen…",
  classLabel: "Klasse",
  classAll: "Alle",
  sortLabel: "Sortierung",
  sortEditorial: "Empfohlen",
  sortPopularity: "Beliebtheit",
  sortName: "Name",
  sortRecent: "Zuletzt aktualisiert",
  rarityLabel: "Seltenheit",
  rarityLegendary: "Legendär",
  rarityMythic: "Mythisch",
  filtersLabel: "Filter",
  clearFilters: "Filter zurücksetzen",
  resultHeroes: "{count} Helden",
  resultSchematics: "{count} Baupläne",
  resultLoadouts: "{count} Loadouts",
  resultGuides: "{count} Guides",
  emptyHeroesTitle: "Keine Helden gefunden",
  emptyHeroesDesc: "Versuche einen anderen Namen, eine andere Klasse oder Seltenheit.",
  emptySchematicsTitle: "Keine Baupläne gefunden",
  emptySchematicsDesc: "Versuche eine andere Suche oder passe die Filter an.",
  emptyLoadoutsTitle: "Keine Loadouts gefunden",
  emptyLoadoutsDesc: "Versuche eine andere Suche oder setze die Filter zurück.",
  emptyGuidesTitle: "Keine Guides gefunden",
  emptyGuidesDesc: "Versuche eine andere Suche oder ein anderes Thema.",
  featuredGuide: "Empfohlener Guide",
  latestGuides: "Neueste Guides",
  readGuide: "Guide lesen",
  topicsLabel: "Themen",
  topicAll: "Alle Themen",
  loading: "Wird geladen…",
  loadError: "Inhalt konnte nicht geladen werden. Bitte erneut versuchen.",
  retry: "Wiederholen",
  viewDetails: "Details ansehen",
  openPreview: "Schnellansicht",
  close: "Schließen",
  commander: "Commander",
  supportTeam: "Support-Team",
  supportSlot: "Support-Slot",
  emptySlot: "Leerer Slot",
  abilities: "Fähigkeiten",
  relatedLoadouts: "Ähnliche Loadouts",
  backToHeroes: "Zurück zu Helden",
  backToLoadouts: "Zurück zu Loadouts",
  categoryLabel: "Kategorie",
  classNameLabel: "Klasse",
});
