import { en, type PublicStrings } from "./public-strings-base";
function withEn(p: Partial<PublicStrings>): PublicStrings {
  return { ...en, ...p };
}
export const pt: PublicStrings = withEn({
  heroesTitle: "Heróis",
  heroesIntro:
    "Explore os Heróis de Save the World: suas classes, raridades, habilidades e vantagens.",
  loadoutsTitle: "Composições",
  loadoutsIntro:
    "Explore composições de Heróis criadas em torno de Comandantes, Heróis de suporte, Vantagens de equipe e equipamento recomendado.",
  schematicsTitle: "Esquemas",
  schematicsIntro:
    "Explore armas e armadilhas, compare seus tipos e vantagens e encontre o equipamento ideal para a sua composição.",
  guidesTitle: "Guias",
  guidesIntro: "Guias, comparações, composições e dicas práticas para Save the World.",
  typeLabel: "Tipo",
  typeAll: "Todos",
  typeWeapon: "Armas",
  typeTrap: "Armadilhas",
  perksLabel: "Vantagens",
  perkSlotLabel: "Espaço",
  backToSchematics: "Voltar aos Esquemas",
  weaponLabel: "Arma",
  trapLabel: "Armadilha",
  subtypeLabel: "Subtipo",
  placementLabel: "Posicionamento",
  searchLabel: "Pesquisar",
  searchPlaceholder: "Pesquisar por nome…",
  classLabel: "Classe",
  classAll: "Todos",
  sortLabel: "Ordenar",
  sortEditorial: "Destaques",
  sortPopularity: "Popularidade",
  sortName: "Nome",
  sortRecent: "Atualizado recentemente",
  rarityLabel: "Raridade",
  rarityLegendary: "Lendário",
  rarityMythic: "Mítico",
  filtersLabel: "Filtros",
  clearFilters: "Limpar filtros",
  resultHeroes: "{count} Heróis",
  resultSchematics: "{count} Esquemas",
  resultLoadouts: "{count} Composições",
  resultGuides: "{count} Guias",
  emptyHeroesTitle: "Nenhum Herói encontrado",
  emptyHeroesDesc: "Tente outro nome, classe ou raridade.",
  emptySchematicsTitle: "Nenhum Esquema encontrado",
  emptySchematicsDesc: "Tente outra pesquisa ou ajuste os filtros.",
  emptyLoadoutsTitle: "Nenhuma Composição encontrada",
  emptyLoadoutsDesc: "Tente outra pesquisa ou limpe os filtros.",
  emptyGuidesTitle: "Nenhum Guia encontrado",
  emptyGuidesDesc: "Tente outra pesquisa ou explore outro tema.",
  featuredGuide: "Guia em destaque",
  latestGuides: "Últimos guias",
  readGuide: "Ler guia",
  topicsLabel: "Temas",
  topicAll: "Todos os temas",
  loading: "Carregando…",
  loadError: "Não foi possível carregar o conteúdo. Tente novamente.",
  retry: "Tentar novamente",
  viewDetails: "Ver detalhes",
  openPreview: "Visualização rápida",
  close: "Fechar",
  commander: "Comandante",
  supportTeam: "Equipe de suporte",
  supportSlot: "Espaço de suporte",
  emptySlot: "Espaço vazio",
  abilities: "Habilidades",
  relatedLoadouts: "Composições relacionadas",
  backToHeroes: "Voltar aos heróis",
  backToLoadouts: "Voltar às composições",
  categoryLabel: "Categoria",
  classNameLabel: "Classe",
});
export const zh: PublicStrings = withEn({
  heroesTitle: "英雄",
  heroesIntro: "探索 Save the World 英雄的职业、稀有度、技能与特长。",
  loadoutsTitle: "阵容",
  loadoutsIntro: "探索以指挥官、支援英雄、团队特长和推荐装备为核心搭配的阵容。",
  schematicsTitle: "蓝图",
  schematicsIntro: "浏览武器与陷阱，比较它们的类型与特长，找到适合你阵容的装备。",
  guidesTitle: "指南",
  guidesIntro: "Save the World 指南、对比、配装与实用技巧。",
  typeLabel: "类型",
  typeAll: "全部",
  typeWeapon: "武器",
  typeTrap: "陷阱",
  perksLabel: "特长",
  perkSlotLabel: "槽位",
  backToSchematics: "返回蓝图",
  weaponLabel: "武器",
  trapLabel: "陷阱",
  subtypeLabel: "子类型",
  placementLabel: "放置位置",
  searchLabel: "搜索",
  searchPlaceholder: "按名称搜索…",
  classLabel: "职业",
  classAll: "全部",
  sortLabel: "排序",
  sortEditorial: "推荐",
  sortPopularity: "人气",
  sortName: "名称",
  sortRecent: "最近更新",
  rarityLabel: "稀有度",
  rarityLegendary: "传奇",
  rarityMythic: "神话",
  filtersLabel: "筛选",
  clearFilters: "清除筛选",
  resultHeroes: "{count} 位英雄",
  resultSchematics: "{count} 个蓝图",
  resultLoadouts: "{count} 套阵容",
  resultGuides: "{count} 篇指南",
  emptyHeroesTitle: "未找到英雄",
  emptyHeroesDesc: "试试其他名称、职业或稀有度。",
  emptySchematicsTitle: "未找到蓝图",
  emptySchematicsDesc: "试试其他搜索词或调整筛选条件。",
  emptyLoadoutsTitle: "未找到阵容",
  emptyLoadoutsDesc: "试试其他搜索词或清除筛选条件。",
  emptyGuidesTitle: "未找到指南",
  emptyGuidesDesc: "试试其他搜索词或浏览其他主题。",
  featuredGuide: "精选指南",
  latestGuides: "最新指南",
  readGuide: "阅读指南",
  topicsLabel: "主题",
  topicAll: "全部主题",
  loading: "加载中…",
  loadError: "无法加载内容，请重试。",
  retry: "重试",
  viewDetails: "查看详情",
  openPreview: "快速预览",
  close: "关闭",
  commander: "指挥官",
  supportTeam: "支援小队",
  supportSlot: "支援槽位",
  emptySlot: "空槽位",
  abilities: "技能",
  relatedLoadouts: "相关阵容",
  backToHeroes: "返回英雄列表",
  backToLoadouts: "返回阵容列表",
  categoryLabel: "分类",
  classNameLabel: "职业",
});
